### ISSUE TITLE
Broken in Deno 2.0

### ISSUE THREAD

**Issue by gibbygano** [Vehmloewff/hackle#4]
Not sure if this project is still maintained, but just in case: 
Deno 2.0 no longer allows the `window` global variable. 

```
error: Uncaught (in promise) ReferenceError: window is not defined
if (!window.hackle) window.hackle = makeHackle()
^
    at https://deno.land/x/hackle@1.1.1/init.ts:9:1

    info: window global is not available in Deno 2.
    hint: Replace `window` with `globalThis`.
```

I don't use hackle directly, but a consumer of hackle, [fresh-seo](https://github.com/xstevenyung/fresh-seo). 
Thought I'd reach out on the off chance the maintainer still monitors the issues.

**Comment by ghost** [comment]
Also having this issue, I'm not even using `fresh-seo` so I think it's a direct dependency of Fresh.

**Comment by gibbygano** [comment]
> Also having this issue, I'm not even using `fresh-seo` so I think it's a direct dependency of Fresh.

It's definitely not in fresh. I confirmed in their repo while I was trying to find the actual consumer.  Also, after removing fresh-seo the issue was resolved for me.  This was on latest fresh (1.7.3) and the previous (1.7.2). You might have another dependency that is consuming it.

**Comment by ghost** [comment]
Hmm I have no idea what it might be, is there a quick way to look at the dependencies of a package using Deno?

**Comment by gibbygano** [comment]
> Hmm I have no idea what it might be, is there a quick way to look at the dependencies of a package using Deno?

With fresh-seo it wasn't even referenced in any of their ts files or deno.json. It was only in the deno.lock which is apparently still enough to break things. I had to go to each plugin/package I had and search their repo for "hackle" to find it. 

Edit: in case it is directly consumed by a dependency this is how you check:
```

deno info <package/plugin>

```

Make sure to include the npm: or jsr: prefix if that is how you're consuming the dependency.

**Comment by ghost** [comment]
Seems mine is a dependency chain up to `fresh-seo` and then again to `fresh/plugins/tailwind.ts` which is a little annoying.

Also if you run `deno info main.ts` it will display the full dependency tree which is great.

**Comment by scsmash3r** [comment]
> Also having this issue, I'm not even using `fresh-seo` so I think it's a direct dependency of Fresh.

Fixed here: https://github.com/scsmash3r/fresh-seo
Now waiting for PR from original repo owner :) In any case, I'll continue to develop my fork and will toss PRs, since I need this plugin for my live project.

**Comment by Vehmloewff** [comment]
Whoa, I had no idea that this was in fresh-seo's module graph (my apologies for being late to the party). I fixed the issue downstream in glob-filter (see https://github.com/xstevenyung/fresh-seo/issues/27#issuecomment-2566625142 and https://github.com/Vehmloewff/glob-filter/commit/d09c2fb932724d24937f1e2b86a38873cbcbe69c).

This module is still broken though, and I am going deprecate it instead of fixing it. This was project was written at a time when Deno was very new, but now all of the great NodeJS loggers are available, in addition to the [official logging framework from the standard library](https://jsr.io/@std/log).

This project has reached it's end of life.
